// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgtkzsrlaRGdhOwFFSSvB4FRcAmFz1_LA',
    appId: '1:784822751901:web:be5ff49a5f033a1da5fa74',
    messagingSenderId: '784822751901',
    projectId: 'prova-5b69a',
    authDomain: 'prova-5b69a.firebaseapp.com',
    storageBucket: 'prova-5b69a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgtkzsrlaRGdhOwFFSSvB4FRcAmFz1_LA',
    appId: '1:784822751901:android:be5ff49a5f033a1da5fa74',
    messagingSenderId: '784822751901',
    projectId: 'prova-5b69a',
    storageBucket: 'prova-5b69a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgtkzsrlaRGdhOwFFSSvB4FRcAmFz1_LA',
    appId: '1:784822751901:ios:be5ff49a5f033a1da5fa74',
    messagingSenderId: '784822751901',
    projectId: 'prova-5b69a',
    storageBucket: 'prova-5b69a.firebasestorage.app',
    iosBundleId: 'com.prova.donaduzzi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgtkzsrlaRGdhOwFFSSvB4FRcAmFz1_LA',
    appId: '1:784822751901:ios:be5ff49a5f033a1da5fa74',
    messagingSenderId: '784822751901',
    projectId: 'prova-5b69a',
    storageBucket: 'prova-5b69a.firebasestorage.app',
    iosBundleId: 'com.prova.donaduzzi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgtkzsrlaRGdhOwFFSSvB4FRcAmFz1_LA',
    appId: '1:784822751901:web:be5ff49a5f033a1da5fa74',
    messagingSenderId: '784822751901',
    projectId: 'prova-5b69a',
    authDomain: 'prova-5b69a.firebaseapp.com',
    storageBucket: 'prova-5b69a.firebasestorage.app',
  );
}
