// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA60rpcjwU7Suzwjo1BI3SDEKa0O87kaH0',
    appId: '1:526891742329:web:86e16eefece6b4b1df10a8',
    messagingSenderId: '526891742329',
    projectId: 'banco-de-questoes-cdc6b',
    authDomain: 'banco-de-questoes-cdc6b.firebaseapp.com',
    databaseURL: 'https://banco-de-questoes-cdc6b-default-rtdb.firebaseio.com',
    storageBucket: 'banco-de-questoes-cdc6b.firebasestorage.app',
    measurementId: 'G-CXG0D2F7SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA60rpcjwU7Suzwjo1BI3SDEKa0O87kaH0',
    appId: '1:526891742329:android:86e16eefece6b4b1df10a8',
    messagingSenderId: '526891742329',
    projectId: 'banco-de-questoes-cdc6b',
    databaseURL: 'https://banco-de-questoes-cdc6b-default-rtdb.firebaseio.com',
    storageBucket: 'banco-de-questoes-cdc6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA60rpcjwU7Suzwjo1BI3SDEKa0O87kaH0',
    appId: '1:526891742329:ios:86e16eefece6b4b1df10a8',
    messagingSenderId: '526891742329',
    projectId: 'banco-de-questoes-cdc6b',
    databaseURL: 'https://banco-de-questoes-cdc6b-default-rtdb.firebaseio.com',
    storageBucket: 'banco-de-questoes-cdc6b.firebasestorage.app',
    androidClientId:
        '526891742329-moo832g7enr7m5vnjau9ec4f0kdaarcg.apps.googleusercontent.com',
    iosClientId:
        '526891742329-ismost5v0dctrh80be6tp6lturti1109.apps.googleusercontent.com',
    iosBundleId: 'com.exemplo.prova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA60rpcjwU7Suzwjo1BI3SDEKa0O87kaH0',
    appId: '1:526891742329:ios:86e16eefece6b4b1df10a8',
    messagingSenderId: '526891742329',
    projectId: 'banco-de-questoes-cdc6b',
    databaseURL: 'https://banco-de-questoes-cdc6b-default-rtdb.firebaseio.com',
    storageBucket: 'banco-de-questoes-cdc6b.firebasestorage.app',
    androidClientId:
        '526891742329-moo832g7enr7m5vnjau9ec4f0kdaarcg.apps.googleusercontent.com',
    iosClientId:
        '526891742329-ismost5v0dctrh80be6tp6lturti1109.apps.googleusercontent.com',
    iosBundleId: 'com.exemplo.prova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA60rpcjwU7Suzwjo1BI3SDEKa0O87kaH0',
    appId: '1:526891742329:web:86e16eefece6b4b1df10a8',
    messagingSenderId: '526891742329',
    projectId: 'banco-de-questoes-cdc6b',
    authDomain: 'banco-de-questoes-cdc6b.firebaseapp.com',
    databaseURL: 'https://banco-de-questoes-cdc6b-default-rtdb.firebaseio.com',
    storageBucket: 'banco-de-questoes-cdc6b.firebasestorage.app',
    measurementId: 'G-CXG0D2F7SG',
  );
}
